# Generated by Django 4.2.7 on 2026-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Titulo")),
                ("department", models.CharField(max_length=80, verbose_name="Area")),
                (
                    "location",
                    models.CharField(max_length=120, verbose_name="Localizacao"),
                ),
                (
                    "work_model",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("hibrido", "Hibrido"),
                            ("remoto", "Remoto"),
                        ],
                        default="presencial",
                        max_length=20,
                        verbose_name="Modelo de trabalho",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descricao")),
                ("requirements", models.TextField(verbose_name="Requisitos")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
            ],
            options={
                "verbose_name": "Vaga",
                "verbose_name_plural": "Vagas",
                "ordering": ["-created_at"],
            },
        ),
    ]
