# Generated by Django 4.2.7 on 2026-05-02 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="Nome completo"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("phone", models.CharField(max_length=30, verbose_name="Telefone")),
                (
                    "resume",
                    models.FileField(upload_to="resumes/", verbose_name="Curriculo"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Mensagem")),
                (
                    "lgpd_consent",
                    models.BooleanField(
                        default=False, verbose_name="Consentimento LGPD"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("triagem", "Triagem"),
                            ("entrevista", "Entrevista"),
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                        ],
                        default="novo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Candidatura em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidatura",
                "verbose_name_plural": "Candidaturas",
                "ordering": ["-applied_at"],
            },
        ),
    ]
